### ISSUE TITLE
Change text on the Aeon about page

### ISSUE THREAD

**Issue by erussey** [emory-libraries/archivestech-enhance#3]
Change the text on the [Aeon about page ](https://emorytest.aeon.atlas-sys.com/aeon/aeon.dll?Action=10&Form=1).  Submit a pull request to the Aeon web page Github repository when complete.

Changed text:

**About Aeon** 
Aeon is a software system specially designed to manage circulation for special collections libraries and archives.

Researchers can use it to make an appointment to view rare books and archival collections in Emory's special collections reading rooms, request materials, and submit requests for digitization orders. They can also save requests for future visits and access past requests.  

To get started using Aeon, [log in](https://aeon.library.emory.edu/Logon) with either your Emory account or create a guest account.

**Accessibility**

Emory Libraries is committed to the principles of universal design and strives to provide equitable services online and in our spaces. We assess and enhance the usability and accessibility of our digital interfaces on an ongoing basis, and use Section 508 of the Rehabilitation Act and current WCAG AA standards as benchmarks. For further information, please [contact us ](https://libraries.emory.edu/contact/ask-librarian)or consult Emory’s Department of Accessibility Services.

**Questions, Help, and Feedback**

Please visit our [Help & Contacts page](https://libraries.emory.edu/contact/ask-librarian) for more information about Emory Libraries collections and access.

**Comment by CB987** [comment]
This PR has been approved and merged by Aeon. https://github.com/AtlasSystems-Prod/hosting-aeon-emorysb/pull/15
